---
title: "SEVv2-Screening"
author: "A DuBois"
date: '2022-06-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r packages}
library(tidyverse)
library(readxl)
library(ggplot2)
library(lubridate)

```


# Read in data

```{r read & clean data}

#read in and clean data
Training.df<- read_excel("data/SEV_v2_-_Training_-_Raw_Data.xlsx", sheet = 4, skip = 3) %>%
  transmute(SubjectCode = `Participant Code`,
            SampleName = `Sample Name`,
            TrainRating = `Please mark the perceived intensity of {{sample_name}} exactly as you recorded it on your paper sheet.`
             ) %>%
    filter(SubjectCode != 1130,
           SubjectCode != 1080)

Sess1.df <- read_excel("data/SEV_v2_-_Session_1_-_Raw_Data.xlsx", sheet = 3, skip = 3) %>%
  transmute(SubjectCode = `Participant Code`,
            SampleName = `Sample Name`,
            Rep = `Repetition`,
            SweetRating = `Please take a sip of sample {{sample_code}} and rate the intensity of sweetness only.Sweetness:  the pleasant taste sensation typically produced by sugars (such as sucrose or glucose)`,
            FlavRating = `Please take a sip of sample {{sample_code}} and rate the intensity of flavor only.Flavor: the combined effect of taste sensations, aromas, and chemical feeling factors (e.g. burn of a chili, cooling of menthol) in the mouth.`,
            Presentation = `Position`,
            SampleID = `Sample ID`
            ) %>%
  separate(SampleName, into = c("SampleCode", "Sample"), sep = ". ") %>%
  
  #filter(SubjectCode == 1028)
  
  #filter out testing
  filter(SubjectCode != 1130,
         SubjectCode != 1080
  )
  
Training.df$SubjectCode <- as.factor(Training.df$SubjectCode)

Sess1.df$SubjectCode <- as.factor(Sess1.df$SubjectCode)

```

#SCREENING: Check for correct order in remembered sensations

```{r SCREENING: remembered sensations}


df1 <- Training.df %>%
  separate(SampleName, into = c("TrainingCode", "Sensation"), sep = ". ") %>%
  select(-Sensation) %>%
  group_by(SubjectCode) %>%

  #Make each concentration a column and put the corresponding mean rating value under each respective column
  pivot_wider(names_from = TrainingCode, values_from = TrainRating) %>%
  
  #determine if subject correctly ranked rememebered sensations in order
  transmute(CorrectRank = case_when( A < B & B < C & D < E & E < F ~ "Correct Light & Sound",
                                A < B & B < C ~ "Correct Light",
                                D < E & E < F ~ "Correct Sound", 
                                TRUE ~ "NONE"))


```

#SCREENING: Check TRT of Session 1 data
```{r SCREENING Session 1 TRT analysis}
#Check TRT of sweetness
trtSweet <- Sess1.df %>% 
  select(-c(FlavRating, Sample, Presentation, SampleID)) %>% 
  pivot_wider(names_from = Rep, names_prefix = "Rep", values_from = SweetRating) %>% 
  group_by(SubjectCode) %>% 
  summarise(swTRT = cor(Rep1, Rep2))

#Check TRT of flavor
trtFlav <- Sess1.df %>%
  select(-c(SweetRating, Sample, Presentation, SampleID)) %>%
  pivot_wider(names_from = Rep, names_prefix = "Rep", values_from = FlavRating) %>%
  group_by(SubjectCode) %>%
  summarise(flTRT = cor(Rep1, Rep2))
  
#Print a table with intensity ratings rank check and TRT data
RankTRT <- df1 %>%
  left_join(trtSweet) %>%
  left_join(trtFlav) %>%
  select(SubjectCode, swTRT, flTRT, CorrectRank) %>%
  mutate(Pass = case_when(swTRT > 0.4 & flTRT > 0.4 & CorrectRank == "Correct Light & Sound" ~ "Passed 3/3",
                           swTRT > 0.4 & CorrectRank == "Correct Light & Sound" ~ "Passed 2/3 (Failed Flavor TRT)",
                           flTRT > 0.4 & CorrectRank == "Correct Light & Sound" ~ "Passed 2/3 (Failed Sweet TRT)",
                          swTRT > 0.4 & flTRT > 0.4 & CorrectRank == "Correct Sound" ~ "Passed 2/3 (Failed Light Rank)",
                          swTRT > 0.4 & flTRT > 0.4 & CorrectRank == "Correct Light" ~ "Passed 2/3 (Failed Sound Rank)",
                          swTRT > 0.4 & flTRT > 0.4 & CorrectRank == "NONE" ~ "Check All Training to see if pass",
                          swTRT > 0.4 & CorrectRank == "Correct Sound" ~ "Check Light Training to see if pass",
                          swTRT > 0.4 & CorrectRank == "Correct Light" ~ "Check Sound Training to see if pass",
                          flTRT > 0.4 & CorrectRank == "Correct Sound" ~ "Check Light Training to see if pass",
                          flTRT > 0.4 & CorrectRank == "Correct Light" ~ "Check Sound Training to see if pass",
                          TRUE ~ "Fail")) #%>%
  #arrange(Pass)

```


#SCREENING: Plot TRT data for each subject
```{r SCREENING: plot sweetness and flavor TRTs}

#plot sweetness TRTs for each subject
Sess1.df %>% 
  select(-c(Sample, FlavRating, Presentation, SampleID)) %>%
  pivot_wider(names_from = Rep, names_prefix = "Rep", values_from = SweetRating) %>%
  ggplot(aes(Rep1, Rep2)) +
  geom_point(aes (color = SampleCode)) +
  facet_wrap(~SubjectCode) +
  geom_smooth(method = "lm") +
  geom_text(data = trtSweet, aes(label = round(swTRT, 2), x = 10, y = 60), color = "red") +
  ggtitle("Test-Retest Correlation of Sweetness Ratings") +
  theme_minimal()

#plot flavor TRTs for each subject
Sess1.df %>% 
  select(-c(Sample, SweetRating, Presentation, SampleID)) %>%
  pivot_wider(names_from = Rep, names_prefix = "Rep", values_from = FlavRating) %>%
  ggplot(aes(Rep1, Rep2)) +
  geom_point(aes (color = SampleCode)) +
  facet_wrap(~SubjectCode) +
  geom_smooth(method = "lm") +
  geom_text(data = trtFlav, aes(label = round(flTRT, 2), x = 10, y = 60), color = "red") +
  ggtitle("Test-Retest Correlation of Flavor Ratings") +
  theme_minimal() +
  xlim(0, 100) +
  ylim(0, 100)

#sweet ratings by presentation order, faceted by panelist
Sess1.df %>%
  select(-FlavRating) %>%
  ggplot(aes(Presentation, SweetRating)) +
  geom_point(aes(color = SampleCode)) +
  facet_wrap(~SubjectCode) +
  #theme_minimal() +
  ggtitle("Sweet Ratings in Order of Sample Presentation")

#flavor ratings by presentation order, faceted by panelist
Sess1.df %>%
  select(-SweetRating) %>%
  ggplot(aes(Presentation, FlavRating)) +
  geom_point(aes(color = SampleCode)) +
  facet_wrap(~SubjectCode) +
  #theme_minimal() +
  ggtitle("Flavor Ratings in Order of Sample Presentation")


```
